apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: superbi-web-cd
  namespace: fdp-superbi-web-prod
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - persistentvolumeclaims
      - serviceaccounts
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update