apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: superbi-web-ci
  namespace: fdp-superbi-web-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: superbi-web-ci
subjects:
  - kind: ServiceAccount
    name: superbi-web-ci
    namespace: fdp-superbi-web-prod