#!/bin/bash -e

PAC=__PACKAGE__
CMD="$1"
BASE_DIR=__BASE_DIR__

if [ "$CMD" == "remove" -o "$CMD" == "upgrade" ]; then
	TMP_BAK="/tmp/backup_${PAC}"
	rm -rf $TMP_BAK || true
	mkdir $TMP_BAK
	mv $BASE_DIR $TMP_BAK
fi
