{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- toYaml $secret | nindent 2}}
---
{{- end }}

