
[template]

prefix = "/___CONFIG_SERVICE_BUCKET___"                         # Bucket name that you have defined in config-service

src = "config.yml.tmpl"                                     # Source template name

dest = "/etc/service/___PACKAGE___/___PACKAGE___.yml"                # Destination where you want to copy the generated file (with name and extension)

keys = [
    "/swagger.resourcePackage",
    "/environmentConfig.env",
    "/brv2.oorFlagFilePath"
]